<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Discount extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('discounts')->insert([
            // ====== VOUCHER HỆ THỐNG ======
            [
                'code' => 'GIAM10KSHIP',
                'name' => 'Giảm 10k phí vận chuyển cho đơn từ 50k',
                'discount_value' => 10000,
                'discount_method' => 'fixed',
                'discount_type' => 'freeship',
                'category_id' => null,
                'max_discount_amount' => null,
                'min_order_value' => 50000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(7),
                'status' => 'active',
                'usage_limit' => 9999,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Áp dụng cho đơn từ 50.000đ. Giảm tối đa 10.000đ phí ship.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GIAM5PTMAX20K',
                'name' => 'Giảm 5% tối đa 20k cho đơn hàng đồ ăn từ 100k',
                'discount_value' => 5,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 20000,
                'min_order_value' => 100000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 'active',
                'usage_limit' => 500,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm 5% giá đồ ăn, tối đa 20.000đ. Áp dụng cho đơn từ 100.000đ.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SALEFOOD20PTMAX50K',
                'name' => 'Giảm 20% tối đa 50k cho đơn đồ ăn từ 150k',
                'discount_value' => 20,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 50000,
                'min_order_value' => 150000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(30),
                'status' => 'active',
                'usage_limit' => 1000,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm 20% giá đồ ăn, tối đa 50.000đ. Áp dụng đơn từ 150.000đ.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FREESHIPDON100K',
                'name' => 'Miễn phí vận chuyển (tối đa 15k) cho đơn từ 100k',
                'discount_value' => 15000,
                'discount_method' => 'fixed',
                'discount_type' => 'freeship',
                'category_id' => null,
                'max_discount_amount' => 15000,
                'min_order_value' => 100000,
                'start_date' => Carbon::now()->subDays(3),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 'active',
                'usage_limit' => 2000,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Miễn phí ship tối đa 15.000đ cho đơn từ 100.000đ.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GIAMNGAY30K',
                'name' => 'Giảm ngay 30k cho đơn hàng từ 200k',
                'discount_value' => 30000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => null,
                'min_order_value' => 200000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(1),
                'status' => 'active',
                'usage_limit' => 700,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm ngay 30.000đ cho đơn hàng từ 200.000đ.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NOELVUIVE',
                'name' => 'Giảm 15% tối đa 70k mùa noel (không cần đơn tối thiểu)',
                'discount_value' => 15,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 70000,
                'min_order_value' => 0,
                'start_date' => Carbon::parse('2025-12-01'),
                'end_date' => Carbon::parse('2025-12-25')->endOfDay(),
                'status' => 'active',
                'usage_limit' => 1000,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm 15% tối đa 70.000đ. Không cần giá trị đơn tối thiểu.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DAUHE50K',
                'name' => 'Giảm 50k cho đơn hàng trên 250k (đã hết hạn)',
                'discount_value' => 50000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => null,
                'min_order_value' => 250000,
                'start_date' => Carbon::now()->subMonths(2),
                'end_date' => Carbon::now()->subMonth(),
                'status' => 'inactive',
                'usage_limit' => 500,
                'used' => 150,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Đã hết hạn. Giảm 50.000đ cho đơn trên 250.000đ.',
                'custom_condition_note' => null,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonth(),
            ],
        
            // ====== VOUCHER ĐỔI BẰNG XU ======
            [
                'code' => 'XU30K',
                'name' => 'Giảm ngay 30k khi đổi bằng 1000 xu',
                'discount_value' => 30000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => null,
                'min_order_value' => 100000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 'active',
                'usage_limit' => 300,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1000,
                'condition' => 'Đổi 1000 xu để giảm 30.000đ cho đơn từ 100.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FREESHIPXU15K',
                'name' => 'Free ship tối đa 15k khi đổi bằng 700 xu',
                'discount_value' => 15000,
                'discount_method' => 'fixed',
                'discount_type' => 'freeship',
                'category_id' => null,
                'max_discount_amount' => 15000,
                'min_order_value' => 70000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(14),
                'status' => 'active',
                'usage_limit' => 500,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 700,
                'condition' => 'Đổi 700 xu để miễn phí ship tối đa 15.000đ cho đơn từ 70.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SALEFOODXU20PT',
                'name' => 'Giảm 20% tối đa 40k khi đổi bằng 1500 xu',
                'discount_value' => 20,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 40000,
                'min_order_value' => 120000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 'active',
                'usage_limit' => 200,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1500,
                'condition' => 'Đổi 1500 xu để giảm 20% tối đa 40.000đ. Áp dụng đơn từ 120.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MICAY10K',
                'name' => 'Giảm 10k cho món Mì cay',
                'discount_value' => 10000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => 2, // Mì cay
                'max_discount_amount' => null,
                'min_order_value' => 50000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 'active',
                'usage_limit' => 100,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm 10.000đ cho các món thuộc danh mục Mì cay, đơn từ 50.000đ.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KHAIVI15PT',
                'name' => 'Giảm 15% tối đa 20k cho Khai vị',
                'discount_value' => 15,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => 11, 
                'max_discount_amount' => 20000,
                'min_order_value' => 60000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 'active',
                'usage_limit' => 150,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm 15% (tối đa 20.000đ) cho món Khai vị từ 60.000đ.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GIAIKHAT5K',
                'name' => 'Giảm 5k cho Giải khát',
                'discount_value' => 5000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => 12, 
                'max_discount_amount' => null,
                'min_order_value' => 30000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 'active',
                'usage_limit' => 200,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 300,
                'condition' => 'Giảm 5.000đ cho đồ uống từ danh mục Giải khát.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TOK10PT',
                'name' => 'Giảm 10% cho Lẩu Tokbokki',
                'discount_value' => 10,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => 10, 
                'max_discount_amount' => 15000,
                'min_order_value' => 70000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(12),
                'status' => 'active',
                'usage_limit' => 120,
                'used' => 0,
                'source' => 'system',
                'cost' => 0,
                'condition' => 'Giảm 10% tối đa 15.000đ cho món thuộc danh mục Lẩu Tokbokki.',
                'custom_condition_note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XU20KFOOD',
                'name' => 'Giảm 20k đơn từ 80k khi đổi 800 xu',
                'discount_value' => 20000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => null,
                'min_order_value' => 80000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 'active',
                'usage_limit' => 300,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 800,
                'condition' => 'Đổi 800 xu để giảm 20.000đ cho đơn từ 80.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XU25PTMAX30K',
                'name' => 'Giảm 25% tối đa 30k khi đổi 1200 xu',
                'discount_value' => 25,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 30000,
                'min_order_value' => 100000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 'active',
                'usage_limit' => 200,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1200,
                'condition' => 'Giảm 25% tối đa 30.000đ khi đổi 1200 xu, đơn từ 100.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUFREESHIP20K',
                'name' => 'Free ship tối đa 20k khi đổi 1000 xu',
                'discount_value' => 20000,
                'discount_method' => 'fixed',
                'discount_type' => 'freeship',
                'category_id' => null,
                'max_discount_amount' => 20000,
                'min_order_value' => 90000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(12),
                'status' => 'active',
                'usage_limit' => 250,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1000,
                'condition' => 'Đổi 1000 xu để được miễn phí ship tối đa 20.000đ cho đơn từ 90.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUMICAY15K',
                'name' => 'Giảm 15k cho Mì cay khi đổi 700 xu',
                'discount_value' => 15000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => 2, // Mì cay
                'max_discount_amount' => null,
                'min_order_value' => 60000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 'active',
                'usage_limit' => 100,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 700,
                'condition' => 'Giảm 15.000đ cho các món thuộc danh mục Mì cay. Đơn từ 60.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUTOK20PT',
                'name' => 'Giảm 20% tối đa 25k cho Tokbokki khi đổi 1000 xu',
                'discount_value' => 20,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => 10, // Tokbokki
                'max_discount_amount' => 25000,
                'min_order_value' => 80000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(15),
                'status' => 'active',
                'usage_limit' => 120,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1000,
                'condition' => 'Giảm 20% tối đa 25.000đ cho Tokbokki từ 80.000đ khi đổi 1000 xu.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUKHAIVI10K',
                'name' => 'Giảm 10k cho món Khai vị khi đổi 400 xu',
                'discount_value' => 10000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => 11, // Khai vị
                'max_discount_amount' => null,
                'min_order_value' => 50000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(10),
                'status' => 'active',
                'usage_limit' => 100,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 400,
                'condition' => 'Đổi 400 xu để giảm 10.000đ cho món Khai vị từ 50.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUCOMBO15PT',
                'name' => 'Giảm 15% combo ăn uống khi đổi 1300 xu',
                'discount_value' => 15,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 35000,
                'min_order_value' => 120000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(20),
                'status' => 'active',
                'usage_limit' => 180,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1300,
                'condition' => 'Giảm 15% tối đa 35.000đ cho đơn combo từ 120.000đ khi đổi 1300 xu.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUGIAIKHAT10K',
                'name' => 'Giảm 10k cho đồ uống khi đổi 500 xu',
                'discount_value' => 10000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => 12, // Giải khát
                'max_discount_amount' => null,
                'min_order_value' => 40000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(12),
                'status' => 'active',
                'usage_limit' => 200,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 500,
                'condition' => 'Đổi 500 xu để giảm 10.000đ cho đồ uống từ 40.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XU30PTMAX50K',
                'name' => 'Giảm 30% tối đa 50k khi đổi 1600 xu',
                'discount_value' => 30,
                'discount_method' => 'percent',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => 50000,
                'min_order_value' => 150000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(14),
                'status' => 'active',
                'usage_limit' => 150,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1600,
                'condition' => 'Giảm 30% tối đa 50.000đ cho đơn từ 150.000đ khi đổi 1600 xu.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUSN20K',
                'name' => 'Giảm 20k cho đơn sinh nhật khi đổi 1000 xu',
                'discount_value' => 20000,
                'discount_method' => 'fixed',
                'discount_type' => 'salefood',
                'category_id' => null,
                'max_discount_amount' => null,
                'min_order_value' => 80000,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(5),
                'status' => 'active',
                'usage_limit' => 100,
                'used' => 0,
                'source' => 'point_exchange',
                'cost' => 1000,
                'condition' => 'Áp dụng cho sinh nhật: Giảm 20.000đ khi đổi 1000 xu, đơn từ 80.000đ.',
                'custom_condition_note' => 'Giá trị sử dụng 7 ngày sau kể từ khi đổi mã!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
    }
}
